data_type: raw
feats_type: fbank
feats_config: !include config/feats_config/fbank.yaml
mix_config:
 delay_prob: 1.2
self_corruption:
  num_corrupt: 1
  sampler: uniform
  sampler_config:
    low: 0.2
    high: 0.9
